name: Bug Report
description: Something is not working as expected
title: ''
body:
  - type: markdown
    attributes:
      value: |
        _Please write your bug report in English. Using proper Markdown formatting is highly appreciated, please see this [cheat sheet](https://www.markdownguide.org/cheat-sheet/) for a quick reference._
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of what the bug is or the problem you are encountering.
      placeholder: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: How to reproduce
      description: Please tell us how we can reproduce the bug.
      placeholder: Steps to reproduce.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: Clear and concise description of your expectation.
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: Error message
      description: Do you see a error message? If so, please provide it here.
      render: shell
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: URL
      description: Is the bug you encounter visible on a webpage? If so, please provide it here.
      placeholder: https://example.com
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: If you have any additional context, please put it here. This is also a good place for your screenshots, if any.
    validations:
      required: false